### ISSUE TITLE
可否一次导出所有的聊天数据

### ISSUE THREAD

**Issue by hitech-h** [lqzhgood/Shmily-Get-MobileQQ-Andriod#12]
注意到[可否支持一次解密所有的对话](https://github.com/lqzhgood/Shmily-Get-Wechat/issues/3)
我批量解密数据是用`python`实现的，然而会有些兼容性问题，依旧比较麻烦
想询问一下有无修改源代码上的最优方案
感谢

**Comment by lqzhgood** [comment]
如果有需要我抽空写一个外部的工具用于全部导出吧~   

全量的话其实有很多是不需要的，例如 系统消息（10000） 发送的各种广告和提醒

我觉得把这个作为一个外部库，调用命令行执行 `npm run build` 应该没有什么兼容性问题吧？ 
能否告知一下~

**Comment by hitech-h** [comment]
> 我觉得把这个作为一个外部库，调用命令行执行 `npm run build` 应该没有什么兼容性问题吧？能否告知一下~

其实不太懂，但应该不会有什么问题

**Comment by lqzhgood** [comment]
执行完 `npm run exportTable` 导出数据库 后在 `.\dist\_temp\table\friends.json` 中就有所有好友的数据了。
 
```
for (let i= 0; i< friends; i++) {
      1. 修改 config.js   // rightNum 和 rootPath 
      2. 执行 npm run build 
}
```

最后在 dist 目录就会得到
- /rootPath1
- rootPath1.json
- /rootPath2
- rootPath2.json
- /rootPath3
- rootPath3.json
...

每一对 `rootPath` 都是一个好友的数据(.json)和资源，最后全部丢进 Show 相应的目录即可，Show 默认显示全部信息，如果你要只看一个人的，在搜索中可以筛选。
