### ISSUE TITLE
"friends.json"貌似存在“非列表内好友”信息

### ISSUE THREAD

**Issue by hitech-h** [lqzhgood/Shmily-Get-MobileQQ-Andriod#15]
如果没有理解错的话，`npm run makeAll`是按顺序依次执行`friends.json`内容
在解密过程中发现**部分解密对象不是我的好友**
观察了一下，发现`"groupid": ***`这一信息：

- 当不为列表中的好友时，所值为**负数**；

- 反之，则为**非负数**；

- 这个值与**好友的分组**有关。

**不知`"groupid": ***`为负数的值从何而来**
删除`"groupid": ***`为负数的项之后，所解密的对象就都为我的好友了
不过我并没有观察全部数据，真实情况可能会有所偏差

**Comment by lqzhgood** [comment]
但是我这里 `groupid = -1` 中确实有我认识的~  可能是对方把我删除了（且使用了从对方列表移除的功能）？

总之应该是原来存在于好友列表的人，现在不在了。

这个酌情过滤吧，添加了一行代码，如果需要过滤取消注释就行了。

https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/blob/9fc7040230bf3a9d6a6bd50413c32be18bb8fa4a/tools/makeAll.js#L18-L21
