### ISSUE TITLE
[Bug]聊天语音无法正常转码

### ISSUE THREAD

**Issue by hitech-h** [lqzhgood/Shmily-Get-MobileQQ-Andriod#16]
已更新`decode\typeHandle\audio.js`
除此之外，`decode/typeHandle/addFriend.js`和`tools/makeAll.js`也已更新

在整理数据的时候发现文件数不对，于是查看了上次解码的数据与此次进行对比，发现缺少了`.mp3`文件

上次的截图
<img width="711" alt="屏幕截图 2023-09-16 231216" src="https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/137307061/8be8b3a0-a788-4fe6-8479-9868ea9007e9">
这次的截图
<img width="694" alt="屏幕截图 2023-09-16 231231" src="https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/137307061/80e73ad4-ca82-49cf-9d95-4761344485d5">

应该是属于bug吧……

**Comment by lqzhgood** [comment]
语音有以下三种匹配模式，从高到低，

1. 消息字段有 md5 ，通过 md5 匹配本地（加密的）文件
2. 远程服务器下载漫游语音文件
3. 根据消息字段的目录匹配

一条消息可能同时满足或个别满足以上诺干规则


`1.` 是上次新增的，忘记做解密转码为 mp3 了，因为优先级高，所以大部分匹配到就没有转码

我这没有满足 `1.` 这条规则的消息，代码已更新，麻烦测试一下。 更新 `audio.js` 就可以了

**Comment by hitech-h** [comment]
可以转码了
但发现与上次解密时的**名称**不一致
截图如下
<img width="685" alt="屏幕截图 2023-09-17 125206" src="https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/137307061/b5e2b0d3-64e6-424f-be04-7c3e35ed761e">

在Show里面无法播放，但上次转码的是可以播放的
截图如下
<img width="608" alt="屏幕截图 2023-09-17 125032" src="https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/137307061/25fb1633-7ac6-4cd9-9c60-281c04132f1d">

**Comment by lqzhgood** [comment]
Show 你是用以前的 `.json` 还是新生成的 `.json` ?  

如果是新生成的 `.json`

你按 F12，选择 `控制台 /console` 选项卡
消息头像上右键有一项  `F12打印详细`   然后就会在 `控制台 /console` 打印这条消息的数据

这条消息的  `$MobileQQ.data.mp3Url` 是什么 ?

**Comment by lqzhgood** [comment]
你按 F12，选择 `控制台 /console` 选项卡
消息头像上右键有一项  `F12打印详细`   然后就会在 `控制台 /console` 打印这条消息的数据

这条消息的  `$MobileQQ.data.mp3Url` 是什么 ?

**Comment by hitech-h** [comment]
不好意思，问题已解决，是忘记 **将 `msgData` 复制到 `memoryweb/dist`** 了
F12我也看了，是没问题的

**Comment by lqzhgood** [comment]
调整了一下匹配文件的优先级
还是目录优先把，这样出来的文件名保留原始文件名（含日期），优雅一点。

1. 根据消息字段的目录匹配
2. 消息字段有 md5 ，通过 md5 匹配本地（加密的）文件
3. 远程服务器下载漫游语音文件
