### ISSUE TITLE
no such table: MultiMsgNick

### ISSUE THREAD

**Issue by GreenHatHG** [lqzhgood/Shmily-Get-MobileQQ-Andriod#20]
```javacript
npm run exportTable

> QQ-Mobile-Andriod-Export@1.0.0 exportTable
> node ./tools/exportTable.js


D:\github\Shmily-Get-MobileQQ-Andriod\node_modules\better-sqlite3\lib\methods\wrappers.js:5
        return this[cppdb].prepare(sql, this, false);
                           ^
SqliteError: no such table: MultiMsgNick
    at Database.prepare (D:\github\Shmily-Get-MobileQQ-Andriod\node_modules\better-sqlite3\lib\methods\wrappers.js:5:21)
    at D:\github\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:19:28
    at new Promise (<anonymous>)
    at db.jsonPromise (D:\github\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:18:16)
    at friendMulti (D:\github\Shmily-Get-MobileQQ-Andriod\decode\table\friends.js:28:31)
    at exportTable (D:\github\Shmily-Get-MobileQQ-Andriod\decode\utils\db.js:34:24)
    at D:\github\Shmily-Get-MobileQQ-Andriod\tools\exportTable.js:13:11 {
  code: 'SQLITE_ERROR'
}

Node.js v18.19.0
```

请问一下这个是什么错误呢，是哪个文件没有吗
我other是这样的input\assets\other\com.tencent.tim，直接把tim在android data文件夹下的内容都复制过来了
使用的是android tim3.5.6.3208

```
├── assets
│   └── other
│       └── com.tencent.tim
│           ├── cache
│           ├── files
│           ├── qqstory
│           ├── qsvf
│           ├── qzone
│           └── Tencent
└── data
    ├── databases
    └── files
```

**Comment by lqzhgood** [comment]
这个写的是你数据库中没有 MultiMsgNick 这张表~  这张表应该是群昵称~
这个有点超预期了  你一个群都没有吗?

麻烦截图看一下 .\dist\temp\table\ 下面有哪些文件

**Comment by GreenHatHG** [comment]
> 这个写的是你数据库中没有 MultiMsgNick 这张表~ 这张表应该是群昵称~ 这个有点超预期了 你一个群都没有吗?
> 
> 麻烦截图看一下 .\dist\temp\table\ 下面有哪些文件

![image](https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/34258355/b609dbc6-f75c-41b5-a2be-dd3ee23f2629)
tim有群的

**Comment by lqzhgood** [comment]
更新一下这个几个文就可以了,  暂时跳过这个表~
![image](https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/9134671/6a6671ae-d086-4acc-a8e2-f6319bc642de)

然后把下面两个发我邮箱看看
内容是表名

- dist\_temp\table\tables-main.json
- dist\_temp\table\tables-slow.json

**Comment by GreenHatHG** [comment]
> 更新一下这个几个文就可以了, 暂时跳过这个表~ ![image](https://private-user-images.githubusercontent.com/9134671/294925919-6a6671ae-d086-4acc-a8e2-f6319bc642de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjE5NDMsIm5iZiI6MTcwNDc2MTY0MywicGF0aCI6Ii85MTM0NjcxLzI5NDkyNTkxOS02YTY2NzFhZS1kMDg2LTRhY2MtYThlMi1mNjMxOWJjNjQyZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMDA1NDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDVkOGU0NTNiM2VhYjA0OTY2YmNjZmJhMWRkN2I1MWFhMGY5OGQ0ZTRkNDk5ZmFlNmMwZTFjMjkzYWRmYjFmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VVEcz5DgtEqs1ah1rOb_AlcPyS8UVRcpb__iqyYW6w0)
> 
> 然后把下面两个发我邮箱看看 内容是表名
> 
> * dist_temp\table\tables-main.json
> * dist_temp\table\tables-slow.json

已发
![image](https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/34258355/7d5f4d0c-6ae5-4be1-a46d-d84459cdf8d2)

**Comment by lqzhgood** [comment]
对比了一下, 少了很多表~~   不知道为啥.... 
不过都不是核心的表,  先做空处理吧.
