### ISSUE TITLE
运行npm run exportTable时报错

### ISSUE THREAD

**Issue by hionwi** [lqzhgood/Shmily-Get-MobileQQ-Andriod#25]
![image](https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/53936026/dec9a199-1354-4633-8e3e-04a52a5c3f76)

**Comment by lqzhgood** [comment]
修好了, 更新一下 `tools\exportTable.js` 这个文件即可.

或者手动创建一下 `dist\_temp\table` 这个目录也行
