### ISSUE TITLE
errors:865

### ISSUE THREAD

**Issue by jgbrzzh** [lqzhgood/Shmily-Get-MobileQQ-Andriod#27]
![屏幕截图 2024-08-12 143617](https://github.com/user-attachments/assets/766a6fb5-aee4-4546-8961-bb8b12ad8495)
我在使用您的软件时遇到了一些问题，希望您能够帮助解决。谢谢！
运行npm run build时反复卡在第8268条消息
报错如上所示

**Comment by jgbrzzh** [comment]
![屏幕截图 2024-08-12 155330](https://github.com/user-attachments/assets/fa681ad1-67dd-4c5e-bcf6-34458e3db52b)
以管理员身份运行且去掉路径中的空格后

**Comment by lqzhgood** [comment]
解码这一条的音频文件出错的。 
要么你把这一条音频文件单独拿出来用 https://github.com/Coldison/silk2mp3 处理看看有问题不。

**Comment by jgbrzzh** [comment]
![屏幕截图 2024-08-12 164203](https://github.com/user-attachments/assets/f64cb95f-9ecd-494c-b22f-5d7b213c5d48)
ptt文件夹中所有文件均成功转换

**Comment by jgbrzzh** [comment]
在手动将ptt文件夹中的文件解码替换为mp3格式后不再卡在第8268条消息

**Comment by jgbrzzh** [comment]
但构建完成后语音全部无法播放

**Comment by lqzhgood** [comment]
> 在手动将ptt文件夹中的文件解码替换为mp3格式后不再卡在第8268条消息

你是直接改扩展名的意思吗？ 这样是不行的，因为 ptt 文件中都是加密的， 需要解密才能转 mp3.

你在 83 行 
https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/blob/fb6df86a236cb88c14a15300a2c3758420080c5b/decode/typeHandle/audio.js#L83

加一个 
```
console.log(targetFile, targetDir, name);
await slkToMp3(targetFile, targetDir, name);
```

然后就会输出报错的音频文件， 你把这个文件发给我吧。

**Comment by lqzhgood** [comment]
i@lqzh.me

**Comment by jgbrzzh** [comment]
您好，感谢回复，我是通过 https://github.com/Coldison/silk2mp3 将ptt文件夹中的语音转化为mp3后继续以相同文件名放在ptt文件夹中，并且将未解密的原文件删除
用以上方法产生的D:\ChatInformation\Shmily-Get-MobileQQ-Andriod-main\dist\data\MobileQQ-Android-   ***  (对方QQ)-20240812\audio\  ***  (我的QQ)
文件夹中存在mp3格式文件并且能通过potplayer正常播放

bug正在复现中，稍后相关文件将会发送至您的邮箱，谢谢

**Comment by jgbrzzh** [comment]
已发送

**Comment by jgbrzzh** [comment]
顺便提一下另外一个bug，用 https://github.com/lqzhgood/Shmily-Show/ 构建后的成品图片也无法正常显示，但  D:\ChatInformation\Shmily-Show-main\memoryweb\dist\data\data\MobileQQ-Android-***-20240812\image 
文件夹中也存在对应的可用ps打开的图片文件

**Comment by lqzhgood** [comment]
你这个文件我测试正常的呀.
感觉是路径有问题吧.  因为我看到截图里路径是乱码.

去掉路径空格 使用非管理员运行 也报错吗?

**Comment by jgbrzzh** [comment]
稍等
我再来试一下

**Comment by lqzhgood** [comment]
项目目录下,  把下面代码写入 1.txt, 
同时把问题 `238EA3B4D4783592FF3E9FC06B4EC680` 文件放在同样目录  

```js
const slkToMp3 = require('slk-to-mp3');

(async () => {
    await slkToMp3('./238EA3B4D4783592FF3E9FC06B4EC680', './', '123');
})();
```

执行 `node 1.txt` 看看会报错不?
如果正常,会生成 `1.mp3` 的文件

**Comment by jgbrzzh** [comment]
没有发生报错

**Comment by jgbrzzh** [comment]
可能是路径问题
![屏幕截图 2024-08-13 091902](https://github.com/user-attachments/assets/9604163f-ab6b-4858-9939-e408878600ff)
我在另一个相似项目下尝试提取，所有语音文件都是路径报错

**Comment by lqzhgood** [comment]
那应该就没问题了, 你检查下路径有不有特殊字符把,  删掉空字符啥的.


测试下, 确实含空格的路径有问题.

**Comment by jgbrzzh** [comment]
好的，谢谢

**Comment by jgbrzzh** [comment]
> 你这个文件我测试正常的呀. 感觉是路径有问题吧. 因为我看到截图里路径是乱码.
> 
> 去掉路径空格 使用非管理员运行 也报错吗?




去掉路径空格 使用非管理员运行 依然报错



```
D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main>npm run exportTable

 QQ-Mobile-Andriod-Export@1.0.0 exportTable
 node ./tools/exportTable.js


D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main>npm run md5assets

 QQ-Mobile-Andriod-Export@1.0.0 md5assets
 node ./tools/assetsFileMd5.js

ok 7099

D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main>npm run build

 QQ-Mobile-Andriod-Export@1.0.0 build
 cross-env NODE_ENV=production node index.js
progress [======================------------------] 54% | ETA: 1524s | 8268/15301D:\ChatInformation\chatpromax20240812\0
node:internal/errors:865
  const err = new Error(message);
              ^

Error: Command failed: D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\node_modules\ffmpeg-stati3
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at silkToMp3 (D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\node_modules\slk-to-mp3\index.)
    at convert (D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\node_modules\slk-to-mp3\index.js)
    at audio (D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\decode\typeHandle\audio.js:84:19)
    at typeMap (D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\decode\typeMap.js:101:36)
    at ToMsg (D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\decode\index.js:29:50)
    at async D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\index.js:50:20 {
  status: 1,
  signal: null,
  output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
  pid: 21032,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(0) [Uint8Array] []
}

Node.js v18.18.2
```


相关目录
D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main
D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\input\assets\ptt\1010101010（我的QQ）（假）

**Comment by jgbrzzh** [comment]
https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/issues/9#issuecomment-1649476691)

采用了以上方法后：

![image](https://github.com/user-attachments/assets/55cd64c3-a6ff-4f98-89fd-c6dd2efb68e2)

**Comment by jgbrzzh** [comment]
直到8271消息类型才是语音

**Comment by lqzhgood** [comment]
```
console.log(targetFile, targetDir, name);
await slkToMp3(targetFile, targetDir, name);
```

这里输出的 targetFile, targetDir, name, 拼接到下面文件直接执行.

斜杠要转换方向, 变为这样 `E:/Git/Shmily-Get-MobileQQ-Andriod-123123/dist/data/Mobil......`


```
const slkToMp3 = require('slk-to-mp3');

(async () => {
    await slkToMp3(targetFile, targetDir, name);
})();
```

**Comment by jgbrzzh** [comment]
能够再详细一点吗，谢谢

**Comment by lqzhgood** [comment]
> > 在手动将ptt文件夹中的文件解码替换为mp3格式后不再卡在第8268条消息
> 
> 你是直接改扩展名的意思吗？ 这样是不行的，因为 ptt 文件中都是加密的， 需要解密才能转 mp3.
> 
> 你在 83 行
> 
> https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/blob/fb6df86a236cb88c14a15300a2c3758420080c5b/decode/typeHandle/audio.js#L83
> 
> 加一个
> 
> ```
> console.log(targetFile, targetDir, name);
> await slkToMp3(targetFile, targetDir, name);
> ```
> 
> 然后就会输出报错的音频文件， 你把这个文件发给我吧。



> 项目目录下, 把下面代码写入 1.txt, 同时把问题 `238EA3B4D4783592FF3E9FC06B4EC680` 文件放在同样目录
> 
> ```js
> const slkToMp3 = require('slk-to-mp3');
> 
> (async () => {
>     await slkToMp3('./238EA3B4D4783592FF3E9FC06B4EC680', './', '123');
> })();
> ```
> 
> 执行 `node 1.txt` 看看会报错不? 如果正常,会生成 `1.mp3` 的文件

这两个结合一下~ 第一个输出的 a,b,c 放到 await slkToMp3('a', 'b', 'c'); 里面

**Comment by jgbrzzh** [comment]
要不你先休息，我之前没有保存输出的变量，现在还要重新运行一下程序

**Comment by jgbrzzh** [comment]
![屏幕截图 2024-08-14 105039](https://github.com/user-attachments/assets/b66e28b5-4c8f-471b-863e-b07095512523)
貌似cmd对console.log输出的每行信息有长度限制，反复运行后不能完全得到三个变量
![屏幕截图 2024-08-14 112354](https://github.com/user-attachments/assets/63d12100-4d9d-49ae-b59a-1fda40f434a7)
修改为此后尝试再次运行
![屏幕截图 2024-08-14 115759](https://github.com/user-attachments/assets/16a808a7-973c-4b16-a4c6-3ef816e95f17)
成功获取

**Comment by jgbrzzh** [comment]
在两个结合起来后依然报错
1.txt
```
const slkToMp3 = require('slk-to-mp3');

(async () => {
    await slkToMp3('D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739/238EA3B4D4783592FF3E9FC06B4EC680', 'D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739', '238EA3B4D4783592FF3E9FC06B4EC680');
})();

```
控制台报错信息

```
Microsoft Windows [版本 10.0.22631.3880]
(c) Microsoft Corporation。保留所有权利。

D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main>node 1.txt
node:internal/errors:865
  const err = new Error(message);
              ^

Error: Command failed: D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\node_modules\ffmpeg-static\ffmpeg.exe -loglevel quiet -y -f s16le -ar 24000 -ac 1 -i D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\dist\data\MobileQQ-Android-95951-20240812\audio\22739\238EA3B4D4783592FF3E9FC06B4EC680.pcm -ar 24000 -b:a 320k D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\dist\data\MobileQQ-Android-95951-20240812\audio\22739\238EA3B4D4783592FF3E9FC06B4EC680.mp3
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at silkToMp3 (D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\node_modules\slk-to-mp3\index.js:24:5)
    at convert (D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\node_modules\slk-to-mp3\index.js:38:9)
    at D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\1.txt:4:11
    at Object.<anonymous> (D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\1.txt:5:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  status: 1,
  signal: null,
  output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
  pid: 5152,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(0) [Uint8Array] []
}

Node.js v18.18.2

D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main>
```
![屏幕截图 2024-08-14 135541](https://github.com/user-attachments/assets/9b736488-0d4f-4914-a030-11416a1db189)

**Comment by jgbrzzh** [comment]
初步怀疑是因为
`D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\dist\data\MobileQQ-Android-95951-20240812\audio\22739\238EA3B4D4783592FF3E9FC06B4EC680.pcm`
下缺少238EA3B4D4783592FF3E9FC06B4EC680.pcm文件
该目录下只存在238EA3B4D4783592FF3E9FC06B4EC680 （无后缀名）

**Comment by jgbrzzh** [comment]
我的尝试：

1. 使用 https://github.com/Coldison/silk2mp3 将ptt文件夹中的无后缀名文件解码为MP3格式
2. 将无后缀名文件与对应的MP3文件复制到
 `D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739`
目录下
3.使用
```
import soundfile as sf
import os

for filename in os.listdir():
    if filename.endswith(".mp3"):
        print(f"处理 {filename}")  
        mp3_filepath = filename
        pcm_filepath = filename[:-4] + ".wav"

        data, samplerate = sf.read(mp3_filepath)
        sf.write(pcm_filepath, data, samplerate)
        print(f"已将 {mp3_filepath} 转换为 {pcm_filepath}")
```
将MP3格式转为pcm（wav后缀）格式
4.利用
```
import os
def rename_files(old_suffix, new_suffix):
    for filename in os.listdir("."):  
        if filename.endswith(old_suffix):
            old_filepath = os.path.join(".", filename)
            new_filename = filename[:-len(old_suffix)] + new_suffix
            new_filepath = os.path.join(".", new_filename)
            os.rename(old_filepath, new_filepath)
            print(f"已将 {filename} 转换为 {new_filename}")
rename_files(".wav", ".pcm") 
```
改后缀名wav为pcm
此时
`D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739`
下存在
![屏幕截图 2024-08-14 134153](https://github.com/user-attachments/assets/16b93e40-3d56-49d9-a6d9-d19efcdf377f)


5.运行node 1.txt
![屏幕截图 2024-08-14 133346](https://github.com/user-attachments/assets/64ef8b20-f744-401a-8db7-2d6c9df16b22)
无报错
且`D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739`
中文件变为
![屏幕截图 2024-08-14 133933](https://github.com/user-attachments/assets/5f4a5d1c-0fd4-4714-8146-e0ab6a4c82d5)

**Comment by jgbrzzh** [comment]
1.txt
```
const slkToMp3 = require('slk-to-mp3');

(async () => {
    await slkToMp3('D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-2543495951-20240812/audio/2273974181/238EA3B4D4783592FF3E9FC06B4EC680', 'D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-2543495951-20240812/audio/2273974181', '238EA3B4D4783592FF3E9FC06B4EC680');
})();
```

**Comment by jgbrzzh** [comment]
1.txt
```
const slkToMp3 = require('slk-to-mp3');

(async () => {
    await slkToMp3('D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739/238EA3B4D4783592FF3E9FC06B4EC680', 'D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739', '238EA3B4D4783592FF3E9FC06B4EC680');
})();


```

**Comment by jgbrzzh** [comment]
由于我不知道
`Error: Command failed: D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\node_modules\ffmpeg-static\ffmpeg.exe -loglevel quiet -y -f s16le -ar 24000 -ac 1 -i D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\dist\data\MobileQQ-Android-95951-20240812\audio\22739\238EA3B4D4783592FF3E9FC06B4EC680.pcm -ar 24000 -b:a 320k D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\dist\data\MobileQQ-Android-95951-20240812\audio\22739\238EA3B4D4783592FF3E9FC06B4EC680.mp3`
是哪个js抛出的
所以我手动将
`D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739`
中文件全部按以上方式变成（  无后缀名文件 + pcm后缀名文件 ）形式
继续运行`npm run build`
成功 无报错
控制台输出较混乱
![屏幕截图 2024-08-14 143451](https://github.com/user-attachments/assets/2690cecb-9737-48ce-b0eb-9e443e47f417)
`D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739
`
下文件为
![屏幕截图 2024-08-14 143618](https://github.com/user-attachments/assets/a809107d-c0a9-4b4b-b325-cf06a77cbd1b)
且MP3可正常播放

**Comment by lqzhgood** [comment]
那应该就没问题了呀. 所有音频都能通过~~

**Comment by lqzhgood** [comment]
空格路径也修了.   `npm i slk-to-mp3@1.0.1` 可以升级

**Comment by lqzhgood** [comment]
如果还有问题了 把 node_modules 删掉, 执行 `npm i` 重新安装依赖试试吧

**Comment by jgbrzzh** [comment]
好的谢谢

**Comment by jgbrzzh** [comment]
确实没有问题了，用show构建的语音也可正常播放

**Comment by lqzhgood** [comment]
> 确实没有问题了，用show构建的语音也可正常播放

是把 `node_modules` 删掉重新安装依赖就好了吗？

**Comment by jgbrzzh** [comment]
> 我手动将
> D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739
> 中文件全部按以上方式变成（ 无后缀名文件 + pcm后缀名文件 ）形式
> 继续运行npm run build
> 成功 无报错



这样子操作后能够正常生成数据文件和资源文件
用show构建的语音可正常播放

**Comment by jgbrzzh** [comment]
> > 确实没有问题了，用show构建的语音也可正常播放
> 
> 是把 `node_modules` 删掉重新安装依赖就好了吗？

不是

**Comment by lqzhgood** [comment]
搞不懂了， 单独执行这一行 ` await slkToMp3(targetFile, targetDir, name); ` 又是好的， 放程序里又不行。。。。

**Comment by jgbrzzh** [comment]
我也不明白

**Comment by jgbrzzh** [comment]
> 在两个结合起来后依然报错 1.txt
> 
> ```
> const slkToMp3 = require('slk-to-mp3');
> 
> (async () => {
>     await slkToMp3('D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739/238EA3B4D4783592FF3E9FC06B4EC680', 'D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739', '238EA3B4D4783592FF3E9FC06B4EC680');
> })();
> ```
> 
> 控制台报错信息
> 
> ```
> Microsoft Windows [版本 10.0.22631.3880]
> (c) Microsoft Corporation。保留所有权利。
> 
> D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main>node 1.txt
> node:internal/errors:865
>   const err = new Error(message);
>               ^
> 
> Error: Command failed: D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\node_modules\ffmpeg-static\ffmpeg.exe -loglevel quiet -y -f s16le -ar 24000 -ac 1 -i D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\dist\data\MobileQQ-Android-95951-20240812\audio\22739\238EA3B4D4783592FF3E9FC06B4EC680.pcm -ar 24000 -b:a 320k D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\dist\data\MobileQQ-Android-95951-20240812\audio\22739\238EA3B4D4783592FF3E9FC06B4EC680.mp3
>     at checkExecSyncError (node:child_process:890:11)
>     at execSync (node:child_process:962:15)
>     at silkToMp3 (D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\node_modules\slk-to-mp3\index.js:24:5)
>     at convert (D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\node_modules\slk-to-mp3\index.js:38:9)
>     at D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\1.txt:4:11
>     at Object.<anonymous> (D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main\1.txt:5:3)
>     at Module._compile (node:internal/modules/cjs/loader:1256:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>     at Module.load (node:internal/modules/cjs/loader:1119:32) {
>   status: 1,
>   signal: null,
>   output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
>   pid: 5152,
>   stdout: Buffer(0) [Uint8Array] [],
>   stderr: Buffer(0) [Uint8Array] []
> }
> 
> Node.js v18.18.2
> 
> D:\ChatInformation\chatpromax20240812\Shmily-Get-MobileQQ-Andriod-main>
> ```
> 
> ![屏幕截图 2024-08-14 135541](https://private-user-images.githubusercontent.com/142425917/357692973-9b736488-0d4f-4914-a030-11416a1db189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTczMzksIm5iZiI6MTcyMzY5NzAzOSwicGF0aCI6Ii8xNDI0MjU5MTcvMzU3NjkyOTczLTliNzM2NDg4LTBkNGYtNDkxNC1hMDMwLTExNDE2YTFkYjE4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNDQzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2Y4ZGQ5YjNhMTUxN2IwMmFlZWFiNTdlMzczNWQ4MGRjMTFhZGUxMjc4M2FlZWFhODNiNjdjMWVlNjYxMWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IUV9z_BAxXZDve8H-f5j1_WScqxQbXXbpKGyClGdK08)







单独执行node 1.txt一开始也是报错

**Comment by jgbrzzh** [comment]
> 我的尝试：
> 
> 1. 使用 https://github.com/Coldison/silk2mp3 将ptt文件夹中的无后缀名文件解码为MP3格式
> 2. 将无后缀名文件与对应的MP3文件复制到
>    `D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739`
>    目录下
>    3.使用
> 
> ```
> import soundfile as sf
> import os
> 
> for filename in os.listdir():
>     if filename.endswith(".mp3"):
>         print(f"处理 {filename}")  
>         mp3_filepath = filename
>         pcm_filepath = filename[:-4] + ".wav"
> 
>         data, samplerate = sf.read(mp3_filepath)
>         sf.write(pcm_filepath, data, samplerate)
>         print(f"已将 {mp3_filepath} 转换为 {pcm_filepath}")
> ```
> 
> 将MP3格式转为pcm（wav后缀）格式 4.利用
> 
> ```
> import os
> def rename_files(old_suffix, new_suffix):
>     for filename in os.listdir("."):  
>         if filename.endswith(old_suffix):
>             old_filepath = os.path.join(".", filename)
>             new_filename = filename[:-len(old_suffix)] + new_suffix
>             new_filepath = os.path.join(".", new_filename)
>             os.rename(old_filepath, new_filepath)
>             print(f"已将 {filename} 转换为 {new_filename}")
> rename_files(".wav", ".pcm") 
> ```
> 
> 改后缀名wav为pcm 此时 `D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739` 下存在 ![屏幕截图 2024-08-14 134153](https://private-user-images.githubusercontent.com/142425917/357689889-16b93e40-3d56-49d9-a6d9-d19efcdf377f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTczMzksIm5iZiI6MTcyMzY5NzAzOSwicGF0aCI6Ii8xNDI0MjU5MTcvMzU3Njg5ODg5LTE2YjkzZTQwLTNkNTYtNDlkOS1hNmQ5LWQxOWVmY2RmMzc3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNDQzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTUwOThmNWFjOTk1ZWQzYjRiZDQ5NTRlMGYwN2E5OGZlNDIxYzQ1OGQwZjhkMzRlNWYwNTMyMDcwZDZhNmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iQbLVNV85Y6iO0hQt4A8R3avyQYjH-NmzyoyoMbepPs)
> 
> 5.运行node 1.txt ![屏幕截图 2024-08-14 133346](https://private-user-images.githubusercontent.com/142425917/357688305-64ef8b20-f744-401a-8db7-2d6c9df16b22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTczMzksIm5iZiI6MTcyMzY5NzAzOSwicGF0aCI6Ii8xNDI0MjU5MTcvMzU3Njg4MzA1LTY0ZWY4YjIwLWY3NDQtNDAxYS04ZGI3LTJkNmM5ZGYxNmIyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNDQzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWUwODYzNjYzNjgwODgyNWEwN2Y2ZDE4YmYxMmY4OWQ3MTUxNjVmZjUyZDVkMDg1NmRjZjhhMjQzMzljZGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SE_Np9Q0K6g-G3-tKyBUkpzie6i_5N1ydBoavBZPaQ8) 无报错 且`D:/ChatInformation/chatpromax20240812/Shmily-Get-MobileQQ-Andriod-main/dist/data/MobileQQ-Android-95951-20240812/audio/22739` 中文件变为 ![屏幕截图 2024-08-14 133933](https://private-user-images.githubusercontent.com/142425917/357689388-5f4a5d1c-0fd4-4714-8146-e0ab6a4c82d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTczMzksIm5iZiI6MTcyMzY5NzAzOSwicGF0aCI6Ii8xNDI0MjU5MTcvMzU3Njg5Mzg4LTVmNGE1ZDFjLTBmZDQtNDcxNC04MTQ2LWUwYWI2YTRjODJkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNDQzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmY2MDBkYmYzMWJhYjA2Y2Y3OTczYzQzYzE4ZmQ4YmViNDE4MzgwZmM1ZmYyOTRjN2EzMjNmMjYwYTcwNWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UnIhhmVDng-DmoxgEZq3hijlv03d-QIAgy6tzO6XTto)

后来这样子操作一下 
运行node 1.txt就不报错了

**Comment by jgbrzzh** [comment]
可能是我的表述不够清楚
