### ISSUE TITLE
无法正常解密和生成数据

### ISSUE THREAD

**Issue by hitech-h** [lqzhgood/Shmily-Get-MobileQQ-Andriod#4]
您好，我不是程序员，但对电脑有所了解。我在使用您的软件时遇到了一些问题，希望您能够帮助解决。谢谢！

开始"npm i"貌似有问题，用"cnpm"安装的模块
<img width="849" alt="屏幕截图 2023-07-19 224059" src="https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/137307061/6bf1cfbf-4ec2-4eaf-8e3e-7b828eea711e">

”config.js“改了QQ号

可以正常导出数据库和生成资源 MD5
<img width="457" alt="屏幕截图 2023-07-19 224459" src="https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/137307061/2a909c36-5d73-44b0-bc4f-4027181443f9">

然后解密生产数据就出问题了
<img width="1021" alt="屏幕截图 2023-07-19 224609" src="https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/assets/137307061/0791b219-6440-4f94-b670-61ae0468c983">

数据除了视频外都是齐全的（QQ找不到短视频文件在哪）
目录是这样：
input
-assets
--.emotionsm
--chatpic
--ptt
--video
data
-databases
-files
other
-com.tencent.mobileqq
-Tencent

**Comment by lqzhgood** [comment]
由最后的报错信息看到是 `decode/typeHandle/_test.js` 这个文件抛出的。位置为

https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/blob/8c228af92bff6dea9876a62b6f1fcdc8fcf429cc/decode/typeMap.js#L201-L208

你这是一个未解码的未知类型，消息是  0/1564 也就是第一条。

好像这太巧合了，感觉比较复杂~

你能把 `\dist\_temp\table\message.json` 的前30行发到我邮箱吗？或者联系方式发我远程看一下~

**Comment by hitech-h** [comment]
好，发到你邮箱了

**Comment by lqzhgood** [comment]
新增支持类型 `-7012`
https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/commit/9294f6de473765745fd57afd92f8c94309868ca9
